### ISSUE TITLE
bug on station del perro

### ISSUE THREAD

**Issue by bozoweed** [TomGrobbe/FiveM-Trains#1]
hello dear friend i have used the stop station for spawn all metro but the station del perro is buged the two tram is spawning in same way not in front so they have two tram in one can you help me to fix that ?

**Comment by bozoweed** [comment]
finaly i have made print of the vector3 and have the good point sorry

**Comment by ghost** [comment]
You should probably not be using this script anymore since we have discovered how to spawn them natively now. Just use this instead. https://github.com/smallo92/TRAINS

**Comment by TomGrobbe** [comment]
Yeah this resource was never fully supported. It always contained bugs, and you should indeed not be using it anymore. Use the random trains that are managed by the game itself instead.
